version: 2

project_name: edu-auth

builds:
  - id: edu-auth
    main: .
    binary: edu-auth-{{ .Os }}-{{ .Arch }}{{ if eq .Os "windows" }}.exe{{ end }}

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

    flags:
      - -trimpath

    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

    env:
      - CGO_ENABLED=0

archives:
  - id: default
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - CHANGELOG.md

checksum:
  name_template: 'sha1.txt'
  algorithm: sha1
  extra_files:
    - glob: './dist/*.intoto.jsonl'

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"

  name_template: "v0.0.0"

  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"

  header: |
    ## v0.0.0 Build
    
    **构建时间**: {{ .Date }}  
    **提交哈希**: {{ .ShortCommit }}
    
    ---
  
  footer: |
    
    ---
    
    ### 文件校验
    请使用 `sha1.txt` 文件验证下载文件的完整性。
    
    ### SLSA Provenance
    此版本包含 SLSA Level 3 构建证明文件，确保构建过程的安全性和可验证性。

changelog:
  use: github
  sort: asc
  abbrev: 7
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - '^style:'
      - Merge pull request
      - Merge branch

publishers:
  - name: "github"
    env:
      - GITHUB_TOKEN
    cmd: |
      gh release upload {{ .Tag }} {{ .ArtifactPath }}

dist: dist

before:
  hooks:
    - go mod tidy
    - go mod download

snapshot:
  name_template: "{{ incpatch .Version }}-next"

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"