version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: edu-auth
    main: ./main.go
    binary: edu-auth
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    hooks:
      post:
        - bash -c '
            for file in dist/edu-auth_*; do
              if [ -f "$file" ]; then
                basename=$(basename "$file")
                if [[ "$basename" =~ edu-auth_([^_]+)_([^_]+)_(.*) ]]; then
                  os="${BASH_REMATCH[1]}"
                  arch="${BASH_REMATCH[2]}"
                  case "$os" in
                    "windows")
                      newname="edu-auth-windows-${arch}.exe"
                      ;;
                    "darwin")
                      newname="edu-auth-macos-${arch}"
                      ;;
                    "linux")
                      newname="edu-auth-linux-${arch}"
                      ;;
                    *)
                      newname="edu-auth-${os}-${arch}"
                      ;;
                  esac
                  mv "$file" "dist/$newname"
                fi
              fi
            done
          '

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"

checksum:
  disable: true

changelog:
  disable: true

release:
  disable: true

snapshot:
  name_template: "{{ incpatch .Version }}-next"

project_name: edu-auth

git:
  ignore_tags:
    - "{{ .Env.SHORT_SHA }}"